export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const PRE_ADD_FAVORITE = "PRE_ADD_FAVORITE";
export const PRE_REMOVE_FAVORITE = "PRE_REMOVE_FAVORITE";
export const CLEAN_PRE_FAVORITE = "CLEAN_PRE_FAVORITE";

export const FETCH_CATS = "FETCH_CATS";
export const NETWORK_CHECK = "NETWORK_CHECK";
export const FETCH_CAT_IMAGES = "FETCH_CAT_IMAGES";
